### ISSUE TITLE
CUDA warning

### ISSUE THREAD

**Issue by swo** [CDCgov/cfa-viral-lineage-model#20]
```
CUDA-enabled jaxlib is not installed
```

Does this mean we have the wrong version of jax in the lockfile?

**Comment by afmagee42** [comment]
If that's from this:
```
An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
```
I think JAX is just trying to be helpful and thus I don't think we care unless we want to run it on a GPU. And we don't.

**Comment by swo** [comment]
But my GFE laptop has a Nvidia T600 GPU! I want to use that power!

**Comment by afmagee42** [comment]
A GPU is not a guarantee of a speed increase for any arbitrary model. It's easy for computational bottlenecks to form that wipe out any speed gains, and that's in cases where matrix-matrix multiplication is actually the rate-limiting step.
