### ISSUE TITLE
Filter which lineages are modeled

### ISSUE THREAD

**Issue by thanasibakis** [CDCgov/cfa-viral-lineage-model#29]
One assumption that we've been hard-coding and need to make configurable is that we want to model all lineages. (... for the July data I'm playing with, the hierarchical model shows pretty clearly that most of the lineages have negligible proportions.)

_Originally posted by @afmagee42 in https://github.com/CDCgov/cfa-viral-lineage-model/issues/25#issuecomment-2289042751_

**Comment by afmagee42** [comment]
Fixed in #45
