### ISSUE TITLE
Can we shrink forecast plot image sizes?

### ISSUE THREAD

**Issue by thanasibakis** [CDCgov/cfa-viral-lineage-model#40]
https://github.com/CDCgov/cfa-viral-lineage-model/blob/cbc7aa564641e4a173654f2ffe8f345eab9cfd24/present-day-forecasting/main.py#L105-L111

This image is pretty large in size (dimension `24000 × 18000`, taking ~5 seconds to open on a M1 Mac).

Can it be made smaller without impacting visibility?

_(Potential hint: I think I should have set the `units` argument here, and needing to adjust `limitsize` should have clued me in on this)_

**Comment by swo** [comment]
oh, like this is 30x40 *inches*?

**Comment by thanasibakis** [comment]
Indeed 😅

Also, I’m now noticing that my `dpi=300` is somehow ignored, and a DPI of 600 is being used, which certainly does not help
