### ISSUE TITLE
Clean up imports

### ISSUE THREAD

**Issue by afmagee42** [CDCgov/cfa-viral-lineage-model#48]
Our imports are in no particular consistent order, which is a bit confusing.

There should be a pre-commit setting we can toggle to enforce something consistent.

**Comment by thanasibakis** [comment]
Is that true? I've been running `isort` on files as we go, unless I missed something.

But I do agree it would be good to have a pre-commit setting to enforce something

**Comment by afmagee42** [comment]
From `linmod/models.py`

```
import string
from itertools import product
from typing import Iterable

import numpy as np
import numpyro
import numpyro.distributions as dist
import polars as pl
from numpyro.diagnostics import summary
from numpyro.infer.mcmc import MCMC
from plotnine import aes, geom_line, ggplot, theme_bw

from .utils import expand_grid, pl_softmax
```

**Comment by afmagee42** [comment]
This could entirely be _my_ fault as I'm definitely used to pre-commit handling this for me and never having to think about it.

**Comment by thanasibakis** [comment]
Believe it or not, this is actually The Way :)

https://peps.python.org/pep-0008/#imports

**Comment by afmagee42** [comment]
I guess I didn't realize the full ordering precedence differentiated standard library imports from other package ones.

Well, I think it's ugly but it's apparently working.
