### ISSUE TITLE
Simulation output path handling

### ISSUE THREAD

**Issue by afmagee42** [CDCgov/cfa-viral-lineage-model#8]
`run_simulation_study.py` currently writes a csv with the call `.write_csv("out/sim_study.csv")`.

We should (1) check if this directory exists before trying to write to it and (2) create the path in a system-agnostic way (presumably with `os.path.join()`?).

**Comment by swo** [comment]
the pretty way is:
```python
from pathlib import Path
out_path = Path("/path/to/whatever") # you need to discover this in some way
whatever.write_csv(out_path / "sim_study.csv")
```
